spring:
  datasource:
    url: jdbc:postgresql://dpg-cs7fgfjtq21c73c5n7ag-a.oregon-postgres.render.com:5432/my_notes_v115
    username: postgresql
    password: N4NGC7kxXmCO8LXSlYbGK4lApRt8URGi
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
  thymeleaf:
    mode: HTML
    cache: false
