spring.application.name=WeddingDay

spring.datasource.url=jdbc:postgresql://dpg-csc13nhu0jms73efp1cg-a.oregon-postgres.render.com:5432/weddingday_1
spring.datasource.username=anton
spring.datasource.password=xtzeCEGBFvcPwKtUXxI14QUPuIuBAAb6
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
