spring.application.name=WeddingDay

spring.datasource.url=jdbc:postgresql://dpg-cskgs4ij1k6c73c3h3hg-a.oregon-postgres.render.com:5432/weddingday_2
spring.datasource.username=anton
spring.datasource.password=CqvmkdgZ8fWd7bWri0cuV6ucFVkZJbYI
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
