spring.application.name=WeddingDay

spring.datasource.url=jdbc:postgresql://dpg-cs7fgfjtq21c73c5n7ag-a.oregon-postgres.render.com:5432/my_notes_v115
spring.datasource.username=postgresql
spring.datasource.password=${DB_PASSWORD}  # ?????????????? ??????????? ??????
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
