name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: anton
          POSTGRES_PASSWORD: xtzeCEGBFvcPwKtUXxI14QUPuIuBAAb6
          POSTGRES_DB: weddingday_1
        options: >-
          --health-cmd="pg_isready -U postgresql"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'  # Це добре
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://dpg-csc13nhu0jms73efp1cg-a.oregon-postgres.render.com:5432/weddingday_1
          SPRING_DATASOURCE_USERNAME: anton
          SPRING_DATASOURCE_PASSWORD: xtzeCEGBFvcPwKtUXxI14QUPuIuBAAb6
          SPRING_FLYWAY_ENABLED: false  # Додаємо цю змінну для відключення Flyway
        run: mvn test

      # Додати перевірку стилю коду (опційно)
#      - name: Run Checkstyle
#        run: mvn checkstyle:check
